# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: price.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'price.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprice.proto\x12\x05price\"H\n\x0cPriceRequest\x12\x0c\n\x04make\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"-\n\nPriceReply\x12\r\n\x05price\x18\x01 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t2<\n\x06Pricer\x12\x32\n\x08GetPrice\x12\x13.price.PriceRequest\x1a\x11.price.PriceReplyB\x13\xaa\x02\x10\x41utobarn.Pricingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'price_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020Autobarn.Pricing'
  _globals['_PRICEREQUEST']._serialized_start=22
  _globals['_PRICEREQUEST']._serialized_end=94
  _globals['_PRICEREPLY']._serialized_start=96
  _globals['_PRICEREPLY']._serialized_end=141
  _globals['_PRICER']._serialized_start=143
  _globals['_PRICER']._serialized_end=203
# @@protoc_insertion_point(module_scope)
